Repository BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team2, pull requests merged in 2023-04, with the labels that each got.

#46 Feature#37 compare screen
  app/assets/config/manifest.js
  app/assets/stylesheets/components/_component.scss
  app/controllers/comparador_controller.rb
  app/views/partials/_comparador_info.html.erb
  app/views/partials/_comparador_info_to_compare.html.erb
Labels: Sprint 6, Lider Mario

#45 Onlyphones brands page pt.2 #42
  app/controllers/marcas_controller.rb
  app/controllers/onlyphones_controller.rb
  app/views/marcas/index.html.erb
  app/views/partials/_marcas.html.erb
Labels: Sprint 6, Lider Mario

#50 Feature#47 structure and style cart screen
  .vscode/settings.json
  app/assets/stylesheets/components/_component.scss
  app/controllers/cart_controller.rb
  app/views/cart/index.html.erb
  app/views/partials/_phone_card_cart.html.erb
  config/routes.rb
Labels: Sprint 7, Lider Aangel

#57 feature#48-Structure and style of seller phones screen
  app/assets/stylesheets/components/_component.scss
  app/controllers/seller_controller.rb
  app/views/seller/index.html.erb
  config/routes.rb
Labels: Sprint 7, Lider Aangel

#59 Indentation fixed in phone card cart
  app/views/partials/_phone_card_cart.html.erb
Labels: Sprint 8, Lider Alan

#61 Modify READ.md
  README.md
  img/onlyphones-logo.png
  img/onlyphones-page.png
Labels: Sprint 8, Lider Alan

#60 Feature#52 deploy
  app/assets/stylesheets/components/_component.scss
  app/controllers/seller_controller.rb
  app/views/partials/_search_bar_sell.html.erb
  app/views/seller/index.html.erb
  bin/render-build.sh
  config/credentials.yml.enc
  config/environments/production.rb
  config/puma.rb
Labels: Sprint 8, Lider Alan

#63 feature#53-Fix deploy error
  .gitignore
  app/controllers/api_key.rb
Labels: Sprint 8, Lider Alan

#66 Fix deploy error in api_key.rb
  .gitignore
  README.md
  app/assets/stylesheets/components/_component.scss
  app/controllers/api_key.rb
  app/controllers/api_key.rb.example
  app/controllers/marcas_controller.rb
  app/controllers/onlyphones_controller.rb
  app/models/user.rb
  app/views/partials/_search_bar_sell.html.erb
  bin/render-build.sh
  config/application.rb
  config/environments/production.rb
  config/puma.rb
  config/routes.rb
Labels: Sprint 8, Lider Alan

#68 Fix deploy errors
  bin/render-build.sh
Labels: Sprint 8, Lider Alan

#64 Feature#33 about us page
  app/assets/images/samsung-img.jpg
  app/assets/stylesheets/components/_component.scss
  app/assets/stylesheets/pages/_login-form.scss
  app/assets/stylesheets/pages/sign_up_page.scss
  app/controllers/about_us_controller.rb
  app/views/about_us/index.html.erb
  app/views/partials/_footer.html.erb
  app/views/partials/_littlemenu.html.erb
  app/views/partials/_navbar.html.erb
  config/routes.rb
Labels: Sprint 8, Lider Alan

#69 Feature#52-Phone seller view functionality
  Gemfile.lock
  README.md
  app/assets/stylesheets/components/_component.scss
  app/controllers/seller_controller.rb
  app/javascript/controllers/application.js
  app/models/phone.rb
  app/models/user.rb
  app/views/partials/_littlemenu.html.erb
  app/views/partials/_search_bar_sell.html.erb
  app/views/seller/index.html.erb
  config/routes.rb
  db/migrate/20230422230308_add_brand_to_phones.rb
  db/migrate/20230424063910_add_user_to_phones.rb
  db/migrate/20230424185412_add_image_url_to_phones.rb
  db/schema.rb
Labels: Sprint 8, Lider Alan
